name: yesod-form-bootstrap4
version: 3.0.1.1
synopsis: renderBootstrap4
github: ncaq/yesod-form-bootstrap4
license: MIT
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
category: Web

dependencies:
  - base >= 4.7 && < 5
  - blaze-html
  - blaze-markup
  - shakespeare
  - text
  - yesod-core
  - yesod-form

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
