name: yesod-form-bootstrap4
version: 2.1.2
synopsis: renderBootstrap4
github: ncaq/yesod-form-bootstrap4
license: MIT
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
category: Web

dependencies:
  - base >= 4.7 && < 5
  - blaze-html
  - blaze-markup
  - shakespeare
  - text
  - yesod-core
  - yesod-form

ghc-options:
  - -Wall
  # - -Wall-missed-specialisations
  - -Widentities
  # - -Wimplicit-prelude
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  # - -Wmissed-specialisations
  # - -Wmissing-export-lists
  - -Wmissing-exported-signatures
  - -Wmissing-home-modules
  # - -Wmissing-import-lists
  # - -Wmissing-local-signatures
  # - -Wmonomorphism-restriction
  # - -Wpartial-fields
  - -Wredundant-constraints
  - -Wcompat

library:
  source-dirs: src
