version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies for Stack
          keys:
            - v1-stack-{{ checksum "stack.yaml.lock" }}-{{ checksum "package.yaml" }}
            - v1-stack-{{ checksum "stack.yaml.lock" }}-
      - run: stack setup
      - run: stack install --jobs 1 hlint
      - run: stack build --jobs 1 --only-dependencies
      - run: stack build --pedantic
      - save_cache:
          name: Cache Dependencies for Stack
          key: v1-stack-{{ checksum "stack.yaml.lock" }}-{{ checksum "package.yaml" }}
          paths:
            - ~/.stack
            - .stack-work
      - run: hlint --ignore="Parse error" src
