# 現在testは厳密には存在しませんが、
# buildとlintなどをまとめる名前として適切なのはこれだと思います。
# stackで実行するのは確かにtestで、
# 今後パッケージを真面目に開発するならtestも追加します。
name: test
on: push
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: generate
        uses: freckle/stack-action/generate-matrix@v4
    outputs:
      stack-yamls: ${{ steps.generate.outputs.stack-yamls }}
  test:
    needs: generate
    strategy:
      matrix:
        stack-yaml: ${{ fromJSON(needs.generate.outputs.stack-yamls) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-action@v4
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
      - uses: haskell/actions/hlint-setup@v2
      - uses: haskell/actions/hlint-run@v2
